### ISSUE TITLE
'Next' button in /jobs/new/select-workflow does nothing

### ISSUE THREAD

**Issue by dleehr** [Duke-GCB/bespin-ui#145]
Upon creating a new job and selecting a workflow, the **Next** button at /jobs/new/select-workflow does not do anything.

I can select a workflow by clicking **Browse All Versions** first, but the list on the first screen doesn't work

Tested on Safari and Chrome. No error appears in the javascript logs.

**Comment by dleehr** [comment]
Looks like the code is here:

https://github.com/Duke-GCB/bespin-ui/blob/3f4db0b2ea28ed717548ee4765cbf4a26bfd226f/app/controllers/jobs/new/select-workflow.js#L12-L16

**Comment by dleehr** [comment]
Doesn't look like the `workflow` has a `latestEnabledVersion` property:

https://github.com/Duke-GCB/bespin-ui/blob/3f4db0b2ea28ed717548ee4765cbf4a26bfd226f/app/models/workflow.js#L4-L10

@johnbradley any thoughts here? I don't see any logic to compute the `latestEnabledVersion`. Looks like it was removed in 37f96789433d9fa8c5eb79df8979ea51653bbfb6 but I'm not sure what the intent is.

**Comment by johnbradley** [comment]
The `latestEnabledVersion` was the most recent version that could be created within `bespin-ui` (enable_ui=true).
I think this should be:
```
let workflowVersionId = this.get('workflow.latestVersion.id'); 
```
If the latest version isn't enabled in bespin-ui then they will not be able to select it.

Background on these changes in #143
