### ISSUE TITLE
User gets logged out after ~2 minutes.

### ISSUE THREAD

**Issue by johnbradley** [Duke-GCB/bespin-ui#23]
The session authentication works by having bespin-api create a cookie with that is read by bespin-ui. The timeout for this cookie is set to 100 seconds here:
https://github.com/Duke-GCB/bespin-ui/blob/79c58c1bdc579e4db7480603a47c78d94130c3aa/app/session-stores/application.js#L5

One solution would be to upgrade the cookie to a session cookie.

**Comment by dleehr** [comment]
The token itself does not expires, so it's mostly just inconvenient to have an expiration time here. I'll raise this to 2 hours for now, but it will be obsoleted by #48
