### ISSUE TITLE
Document the release/deploy process

### ISSUE THREAD

**Issue by dleehr** [Duke-GCB/bespin-ui#37]
There is a brief (albeit incomplete) section in the README that describes how to build the software for deployment.

However, this misses the part about creating a tag and that travis will actually upload the built tar.gz file to the github release. It's a nicely automated process and I'm already forgetting how it fits together :)

**Comment by dleehr** [comment]
I was looking for a command-line tool to "bump" the version number in the package.json and found that [`npm version`](https://docs.npmjs.com/cli/version) does this. It uses semantic versioning, so running

```
npm version patch
```

will change the version in package.json from `0.1.10` -> `0.1.11`. It also commits the change to the local git repo and creates a tag `v0.1.11`

**Comment by hlapp** [comment]
Perhaps 'npm version' has improved in 3.+ but I've stopped using it. The commit message it creates is too depauperate for the OCD in me, and there is no way to impress on it a pattern for naming tags.

**Comment by dleehr** [comment]
npm version can take an `-m` argument with a printf-format string:

> npm version patch -m "Upgrade to %s for reasons"

But it doesn't appear that you can customize the patternf or naming tags.
