### ISSUE TITLE
Job Errors are still shown after restarting a failed job

### ISSUE THREAD

**Issue by dleehr** [Duke-GCB/bespin-ui#44]
This is misleading/confusing. May be an API issue. Perhaps the errors should be cleared out on restarting a job.

**Comment by johnbradley** [comment]
I would prefer to save the errors so we could troubleshoot what went wrong after the fact.

**Comment by johnbradley** [comment]
They could be moved to some kind of log however so they data model is accurate for the current state. I just don't want to lose that data and sweep problems under the rug.

**Comment by dleehr** [comment]
I agree they should be kept. I filed this as a UI issue because we could simply not show the errors unless the state was `E`. The UI currently shows all errors for the job.

It could be that we're missing a layer (JobInvocation?) that would tie an attempt of a job to the logs and other byproducts.
