### ISSUE TITLE
Authentication improvements

### ISSUE THREAD

**Issue by dleehr** [Duke-GCB/bespin-ui#48]
We discussed this on today's call. The way the auth is working now for bespin-ui, bespin-api, and OAuth is as follows:

1. The [login page shows a button](https://github.com/Duke-GCB/bespin-ui/blob/master/app/templates/login.hbs#L25) that links to `/auth/authorize`
2. `/auth/authorize` is serviced by bespin-api (not bespin-ui) and begins OAuth authorization: https://github.com/Duke-GCB/bespin-api/blob/master/data/views.py#L9
3. Upon successful OAuth authorization, a [DRF Token](http://www.django-rest-framework.org/api-guide/authentication/#tokenauthentication) is found-or-created 
4. The token is [put in a cookie in the response](https://github.com/Duke-GCB/bespin-api/blob/master/data/views.py#L32), in a format that is compatible with ember-simple-auth's cookiestore https://github.com/Duke-GCB/bespin-ui/blob/master/app/session-stores/application.js#L5
5. Subsequent API requests include a `Token xxxxx` header via our [authorizer](https://github.com/Duke-GCB/bespin-ui/blob/master/app/authorizers/drf-token-authorizer.js). This authorizer is configured in the application [adapter](https://github.com/Duke-GCB/bespin-ui/blob/master/app/adapters/application.js#L10).

There are two main issues I see with this:

1. The API layer is providing credentials in a way that is specific to the UI's authentication library implementation. It works because the cookie injected by the API server currently matches what the UI library expects.
2. The CookieStore model in bespin-ui has an expiration time (see #23), but the token is actually permanent. So, even though the UI application discards the token, it continues to be a valid credential and can easily be extracted by a user.
3. The token itself is permanent and we don't have any mechanism to revoke them.

To address these, I suggest

1. bespin-api provides an expiring credential upon OAuth login. This could simply be  [SessionAuthentication](http://www.django-rest-framework.org/api-guide/authentication/#sessionauthentication) or a custom backend
2. bespin-ui stores this credential in the session, rather than a cookie. If this fits into SessionAuthentication, the changes would be minimal
3. For development (non-OAuth), we use this same authentication, rather than the DRF Token authorization.
4. Keep the TokenAuthentication backend enabled in bespin-api, but only for service uses like lando.

@johnbradley, do you recall if there were any security-hardening settings applied to bespin-api that would prevent bespin-ui from reading session data?

**Comment by johnbradley** [comment]
This is what I came across when originally looking at this:
https://docs.djangoproject.com/en/1.11/topics/http/sessions/#using-cookie-based-sessions

> It’s recommended to leave the SESSION_COOKIE_HTTPONLY setting on True to prevent access to the stored data from JavaScript.

**Comment by dleehr** [comment]
Thanks. It may work if the AJAX requests use the same session. Certainly something i'll test.

**Comment by johnbradley** [comment]
Another option for bespin-api temporary tokens: https://bitbucket.org/kbktech/django-rest-framework-temporary-tokens

**Comment by dleehr** [comment]
I'm revisiting this today and examining how others have done it. Some notes:

> bespin-ui stores this credential in the session, rather than a cookie. If this fits into SessionAuthentication, the changes would be minimal

I think I was confused here. Session is a server-side store, keyed by a `sessionid` cookie on the client side. http://www.django-rest-framework.org/api-guide/authentication/#sessionauthentication piggybacks on this server-side session. client requests just need to include `sessionid` and `csrftoken` cookies. `sessionid` is http-only, so it's not readable by javascript

I think I was confusing with https://developer.mozilla.org/en/docs/Web/API/Window/sessionStorage, which is a client-side javascript API for storing data. The lifetime of the data is a "session" (e.g. goes away when window closed). There's also https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage, which is like sessionStorage, but persists. 

In both cases, we'd need to get the token visible to JavaScript somehow (cookie, response header/payload/url so that it could put it in the storage. Both can be vulnerable to XSS attacks, since both APIs can be used by any javascript running under the same domain.

Cookies can be made http-only (as is the recommendation with the `sessionid` cookie). So that would defend against XSS attacks - but since our client application is JavaScript, it needs to read the cookie, so that doesn't help.

Cookies are also sent on every request to their domain, which opens them to CSRF attacks (Hence the CSRF token cycle)

I was curious at what DukeDS is doing, and their model is a little different. The OAuth service redirects to a URL serviced by their react application. So the client-side JS is able to read the oauth token out of the URL. Then it exchanges it for a DukeDS API token, all from the browser. They store the API token in localStorage.

I looked into [JWT](https://github.com/GetBlimp/django-rest-framework-jwt), but don't know that this is necessary. 

It seems like SessionAuthentication is the way to go, since it will adopt the CSRF cookie security from Django. Only issue might be local development where the JS app and the python app run on different ports/hosts. But we can probably keep doing what we're doing for dev.
