### ISSUE TITLE
Attempting to create a job with no name fails without any error

### ISSUE THREAD

**Issue by dleehr** [Duke-GCB/bespin-ui#51]
When creating a job through the UI, it's possible to leave the name field blank.
Clicking the create job button results in a 400 error from the server (that you can view in developer tools), but the UI remains on the job name / file picker screen.

There is no feedback to the user that they must fill in the file name field (or pick files)

I believe ember data does annotate an `errors` property onto the object we attempted to save, so this should be pretty simple to display next to the field.

**Comment by dleehr** [comment]
Also, there are no errors shown for bad or previously used job tokens

**Comment by johnbradley** [comment]
On the post to `/api/job-answer-sets` endpoint `bespin-api` is returning empty `detail` instead of the expected  `{"job_name":["This field may not be blank."]}`.

**Comment by dleehr** [comment]
Was this fixed by #73?

**Comment by johnbradley** [comment]
The main issue was fixed by #65 and https://github.com/Duke-GCB/bespin-api/pull/73.
Not sure about the bad or previously used job tokens errors.
