### ISSUE TITLE
Clean up charge estimates

### ISSUE THREAD

**Issue by dleehr** [Duke-GCB/bespin-ui#52]
Before starting a job, user sees text that they will be charged `$x` per CPU hour. This is shown without any estimate or context as to how many CPU hours are expected, so it will discourage users from clicking start even when we don't currently have plans to charge.

We should profile the jobs to determine estimates, and ultimately show that. But in the short term, we should remove this text.

**Comment by dleehr** [comment]
In the box where we indicate that the results will be made available in Duke Data Service, update the text to indicate it will be shared with the share group for review

**Comment by johnbradley** [comment]
Do we want to include the specific group name or emails in the message?
If so we will need to change bespin-api to let users read this info.

**Comment by dleehr** [comment]
Not individual share users, but just the group name, e.g. 

"Results reviewed by _Group Name_. After review, the results will be delivered to you through Duke Data Service"

**Comment by johnbradley** [comment]
This was fixed by #70.
