### ISSUE TITLE
File Pair Picker tweaks

### ISSUE THREAD

**Issue by dleehr** [Duke-GCB/bespin-ui#55]
UI Feedback on picking files:

- Rename `Read 1` -> `Sample 1`,
- Limit this choice to picking *.fastq or *.fastq.gz
- Parse sample names into a text field and allow them to be renamed

The current component is a file group picker. These changes suggest a more specialized component, likely a subclass.

**Comment by dleehr** [comment]
Parsing the sample names and annotating them into the job will require changes to the underlying workflow to handle them.

**Comment by dleehr** [comment]
Currently, the component is determined by the CWL input type. File[][] -> file-group-list. If we wanted to specialize that file-group-list to something like fastq-pair-list, that customization would apply to all File[][] inputs.

That's probably adequate for now, but we should explore defining a custom CWL type for the array of fastq pairs. Then, bespin-ui could appropriately render a specialized component.

**Comment by johnbradley** [comment]
It would also be nice if the file picker had some kind of loading indicator.
When the user browses to an empty folder they don't know if it's truly empty or just still loading.

**Comment by johnbradley** [comment]
The cwl standard has a `format` parameter that can be used when `type: file`:
http://www.commonwl.org/v1.0/CommandLineTool.html
https://www.biostars.org/p/245091/
I can specify fastq: http://bioportal.bioontology.org/ontologies/EDAM/?p=classes&conceptid=http%3A%2F%2Fedamontology.org%2Fformat_1930#details
Not sure if there is a way to specify fastq.gz but this still might be nice to document.

**Comment by johnbradley** [comment]
Another option is to create a custom type.
Example type declaration:
https://github.com/common-workflow-language/common-workflow-language/blob/1eb152b4ed553e0b92526defa85a8f3e62fdaa41/v1.0/v1.0/schemadef-type.yml#L1-L9

Usage:
https://github.com/common-workflow-language/common-workflow-language/blob/1eb152b4ed553e0b92526defa85a8f3e62fdaa41/v1.0/v1.0/schemadef-wf.cwl#L6-L10

**Comment by johnbradley** [comment]
For now I am going with adding the `format` parameter to the read_pairs: https://github.com/Duke-GCB/bespin-cwl/pull/23

**Comment by johnbradley** [comment]
The remaining issue of users editing the sample names will be handled by #69.
The rest have been fixed via #67.
