### ISSUE TITLE
Paired file picker - support for parsing/editing group names

### ISSUE THREAD

**Issue by johnbradley** [Duke-GCB/bespin-ui#69]
Issue pulled out of #55. UI will be expected to parse filenames user selects and guess the group(sample) names for each pair of files. Users would then need to be able to edit them (for when the guess is wrong). This data would need to be passed to the workflow requiring changes to the workflow to support these inputs. 

One possibility for modeling this data would be to create a custom CWL data type that represents named pairs of files. Example:
```
"named_read_pairs": [
  {
    "name":"SRR099967",
    "read1": {
        "class": "File",
        "path": "...SRR099967_1.fastq.gz"
      },
     "read2": {
        "class": "File",
        "path": "...SRR099967_2.fastq.gz"
      }
   }
  ],
```
A fallback would be to pass the filenames as an array if a data structure like the above is intractable in CWL.

**Comment by dleehr** [comment]
This came up in yesterday's meeting. The current parser derived the sample name **G** for every file in a dataset, requiring the submitter to rename files before submitting the job.

**Comment by johnbradley** [comment]
@dleehr Do you know some of the particular filenames that were incorrectly parsed?

**Comment by dleehr** [comment]
No I don't - maybe ask David about the source project.

**Comment by johnbradley** [comment]
Started looking at allowing users to edit pair names.

### Notes on the current named pairs code

The base class representing the list of named pairs is actually an array of files (content field):
https://github.com/Duke-GCB/bespin-ui/blob/3a99db87acccc74bcfc9d65f2ea64cc7ba1e968c/app/utils/file-item-list.js#L23-L29

There __fileItemGroups__ computed property groups these files into pairs by walking the array:
https://github.com/Duke-GCB/bespin-ui/blob/3a99db87acccc74bcfc9d65f2ea64cc7ba1e968c/app/utils/file-item-list.js#L60-L72

To display the pairs another computed property is created by applying __makeSamplePair__ to the __fileItemGroups__ array:

https://github.com/Duke-GCB/bespin-ui/blob/3a99db87acccc74bcfc9d65f2ea64cc7ba1e968c/app/utils/fastq-file-item-list.js#L59-L64

__makeSamplePair__ currently generates the sample name
https://github.com/Duke-GCB/bespin-ui/blob/3a99db87acccc74bcfc9d65f2ea64cc7ba1e968c/app/utils/fastq-file-item-list.js#L24-L38

There is a separate computed property for what gets put into the CWL job order payload.
https://github.com/Duke-GCB/bespin-ui/blob/3a99db87acccc74bcfc9d65f2ea64cc7ba1e968c/app/utils/fastq-file-item-list.js#L66-L72

**Comment by johnbradley** [comment]
Heard back from our user with example files that were incorrectly parsed:
> G-004_S1_L001_R1.fastq.gz, G-005_S1_L001_R1.fastq.gz…
The sequencing core here at Duke separates out info in the file names by ‘_’ symbols, so if you just wanted to parse by that, it would work for everything sequenced here.
