### ISSUE TITLE
include methods documentation in workflow version details

### ISSUE THREAD

**Issue by johnbradley** [Duke-GCB/bespin-ui#77]
Make use of data describing the workflow.
This will require https://github.com/Duke-GCB/bespin-api/pull/83

**Comment by johnbradley** [comment]
Having trouble getting this to look right.

Methods Document content using a list group:
![screen shot 2017-09-26 at 12 04 15 pm](https://user-images.githubusercontent.com/1024463/30874056-3fcc7382-a2bd-11e7-881c-578a4b17f385.png)

**Comment by johnbradley** [comment]
Methods document content using a well:
![screen shot 2017-09-26 at 1 18 03 pm](https://user-images.githubusercontent.com/1024463/30874095-5b852b8c-a2bd-11e7-925f-e15834a3e5b5.png)

**Comment by dleehr** [comment]
Maybe the `<dl>` with the description/created/URL doesn't belong on a detail page. We could move the created date up to the top with the version and shorten the link text. Then just use the rest of the card for content like

```
### Description

Applies the word count operation...

### Methods

DNA-Seq data...

### References

1. xxx
2. xxx

```

Obviously the two sections come from completely different data models but I think they're mostly describing things at the same level.

**Comment by hlapp** [comment]
FYI, most people authoring papers (of which this methods section would presumably become a part) use a reference manager for references (in part because almost every journal has its own reference formatting rules). Hence, it would save someone a lot of time with the references if they can download them formatted as RIS or BibTeX. Both formats are relatively widely supported among reference managers for importing references.

**Comment by dleehr** [comment]
What version of npm are you using? Looks like my `package-lock.json` woes [are a result of using npm 5](https://stackoverflow.com/questions/44206782/do-i-commit-the-package-lock-json-file-created-by-npm-5). Now that I have 5, an `npm install` seems to ignore `package.json` if `package-lock.json` is present. The markdown stuff isn't included there, so my install fails.

Travis is using npm 3 so it should still be fine there.

**Comment by johnbradley** [comment]
I am using npm version 4.1.2.

**Comment by johnbradley** [comment]
I upgraded npm to 5.4.2.
