### ISSUE TITLE
Indicate if file names will fail

### ISSUE THREAD

**Issue by dleehr** [Duke-GCB/bespin-ui#85]
The single workflow expects a specific file name pattern. If this will cause a failure, we should warn users int he UI

**Comment by dleehr** [comment]
Also warn if no files chosen and files are required.

**Comment by johnbradley** [comment]
Looks like the exomeseq needs to have a check that matches up with https://github.com/Duke-GCB/bespin-cwl/blob/master/tools/parse-read-group-header.cwl.

**Comment by dleehr** [comment]
I was thinking that instead of adding a UI-side check for a specific file name convention (and ensuring uniqueness of sample names), that we might be better off going straight to the custom CWL format described in #69 and #55.

Under that change, the UI would be responsible for providing a name and two files for each "sample". That might be more complicated than it sounds, but it's worth considering if it's worthwhile to do that now.

**Comment by johnbradley** [comment]
Wouldn't it still require some client side code to parse the group names? Otherwise wouldn't the user have to manually enter each group name?

**Comment by dleehr** [comment]
It would. But the current mechanism to derive a read group is pretty basic. It should just be the sample name.

**Comment by johnbradley** [comment]
A custom array type looks like this in packed cwl:
```
{ "type": "array", "items": "#named-file-pair-type.yml/NamedFilePairType" }
```
We can use this here:
https://github.com/Duke-GCB/bespin-ui/blob/19f2c745a136619b73d4c80369598d9e23433e1c/app/utils/component-settings.js#L7

**Comment by dleehr** [comment]
Nice. Short and sweet. One suggestion for the bespin-cwl repo - let's name the file bespin-types.yml and put it in a `types` directory beside `tools` and `workflows`?

**Comment by johnbradley** [comment]
@dleehr I'm going to proceed with the CWL changes. You are welcome to start with the bespin-ui part if you have free time.

**Comment by johnbradley** [comment]
Once loaded with bespin-api loadworkflow `user_fields_json` looks like this: 
```
[{"type": {"type": "array", "items": "NamedFASTQFilePairType"}, "name": "read_pairs"}]
```

So the type for this item is `{"type": "array", "items": "NamedFASTQFilePairType"}`.
